name: 打包Chrome扩展

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: 设置Node.js环境
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: 安装依赖
      run: |
        npm install -g @jsdevtools/file-path-filter
        npm install -g chrome-webstore-upload-cli
        
    - name: 打包扩展
      run: |
        mkdir -p dist
        cp -r popup.html popup.js manifest.json images dist/
        
    - name: 创建ZIP包
      run: |
        cd dist
        zip -r ../cookie_storage_extractor.zip .
        cd ..
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension
        path: cookie_storage_extractor.zip
        
    # 可选: 发布到Chrome Web Store
    # 需要先在GitHub Secrets中设置相关密钥
    # - name: 发布到Chrome Web Store
    #   if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    #   env:
    #     EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
    #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
    #     CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    #     REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
    #   run: |
    #     webstore upload --source cookie_storage_extractor.zip --extension-id $EXTENSION_ID --client-id $CLIENT_ID --client-secret $CLIENT_SECRET --refresh-token $REFRESH_TOKEN
    #     webstore publish --extension-id $EXTENSION_ID --client-id $CLIENT_ID --client-secret $CLIENT_SECRET --refresh-token $REFRESH_TOKEN
    
    # 自动创建GitHub Release
    - name: 创建Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: cookie_storage_extractor.zip 