name: 自动生成变更日志

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: 提取标签名称
        id: extract_tag
        env:
          PR_BODY: ${{ format('{0}/{1}', runner.temp, 'output' ) }}
        run: |
          tag_name=${GITHUB_REF#refs/tags/}
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT

          pr_title="docs: 自动更新 "$tag_name" 的变更日志"
          echo "pr_title=$pr_title" >> $GITHUB_OUTPUT

          latest_stable_tag=$(git tag -l 'v*' | grep -v '-' | grep -v "$tag_name" | sort -V | tail -n 1) # 上一个 stable 版本
          newest_tag=$(git tag -l 'v*' | grep -v "$tag_name" | sort -V | tail -n 1) # 除当前外的最新版本
          echo "latest_stable_tag=$latest_stable_tag" >> $GITHUB_OUTPUT
          echo "newest_tag=$newest_tag" >> $GITHUB_OUTPUT

          if [[ $tag_name == *-* ]]; then # 判断新版本是否为 beta 版本
            latest=$newest_tag            # 若是，则将 latest 参数设置为最新版本
          else
            latest=$latest_stable_tag     # 若否，则设置为上一个 stable 版本
          fi

          echo "latest=$latest" >> $GITHUB_OUTPUT

          cat $GITHUB_OUTPUT

          echo '======='

          echo '新版本标签: '$tag_name >> $PR_BODY
          echo '' >> $PR_BODY
          echo '<details><summary>调试信息</summary>' >> $PR_BODY
          echo '' >> $PR_BODY
          echo '```' >> $PR_BODY
          sed 's/=/: /1' $GITHUB_OUTPUT >> $PR_BODY
          echo '```' >> $PR_BODY
          echo '' >> $PR_BODY
          echo '</details>' >> $PR_BODY

          cat $PR_BODY

      - name: 创建Changelog生成器目录
        run: |
          mkdir -p tools/ChangelogGenerator

      - name: 生成变更日志
        run: |
          git switch master
          python3 tools/ChangelogGenerator/changelog_generator.py --tag "${{ steps.extract_tag.outputs.tag_name }}" --latest "${{ steps.extract_tag.outputs.latest }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 添加文件到Git
        run: |
          git status

          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .

          commit_msg="docs: 自动生成 "${{ steps.extract_tag.outputs.tag_name }}" 的变更日志"
          git commit -m "$commit_msg"

      - name: 创建PR
        uses: peter-evans/create-pull-request@v7
        with:
          sign-commits: true
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.extract_tag.outputs.pr_title }}
          body-path: ${{ format('{0}/{1}', runner.temp, 'output' ) }}
          base: "main"
          branch: "changelog"
          delete-branch: true
          reviewers: |
            about
          assignees: |
            about

      - name: 为发布PR添加审核者
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: ".github/release_reviewers.yaml" 